version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/abstractions"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/authentication/azure"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/serialization/form"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/serialization/multipart"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/serialization/json"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/serialization/text"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/http/fetch"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

- package-ecosystem: npm
  directory: "/packages/test"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    vitest:
      patterns:
        - "*vitest*"

